
CREATE TABLE CareerFields (
    field_id INT AUTO_INCREMENT PRIMARY KEY,
    field_name VARCHAR(255) NOT NULL
);

-- Insert career fields data
INSERT INTO CareerFields (field_name) VALUES
    ('Architecture and Engineering'),
    ('Arts, Culture, and Entertainment'),
    ('Business, Management, and Administration'),
    ('Communications'),
    ('Community and Social Services'),
    ('Education'),
    ('Science and Technology'),
    ('Installation, Repair, and Maintenance'),
    ('Farming, Fishing, and Forestry'),
    ('Government'),
    ('Health and Medicine'),
    ('Law and Public Policy'),
    ('Sales');

-- Create a table to store job positions
CREATE TABLE JobPositions (
    job_id INT AUTO_INCREMENT PRIMARY KEY,
    job_name VARCHAR(255) NOT NULL,
    field_id INT,
    FOREIGN KEY (field_id) REFERENCES CareerFields(field_id)
);

-- Insert job positions data
INSERT INTO JobPositions (job_name, field_id) VALUES
    ('Architect', 1),
    ('Civil Engineer', 1),
    ('Landscape Architect', 1),
    ('Sustainable Designer', 1),
    ('Biomedical Engineer', 1),
    ('Singer/Songwriter', 2),
    ('Music Producer', 2),
    ('Art Curator', 2),
    ('Animator/Video Game Designer', 2),
    ('Filmmaker', 2),
    ('Graphic Designer', 2),
    ('Fashion Designer', 2),
    ('Photographer', 2),
    ('Human Resources Manager', 3),
    ('Marketing Assistant', 3),
    ('Accountant', 3),
    ('Secretary', 3),
    ('Entrepreneur/Small Business Owner', 3),
    ('Real Estate Agent', 3),
    ('Business Development Manager', 3),
    ('Journalist', 4),
    ('Copywriter', 4),
    ('Communications Manager', 4),
    ('Public Relations Specialist', 4),
    ('Meeting/Event Planner', 4),
    ('Social Media Manager', 4),
    ('Brand Manager', 4),
    ('School Counselor', 5),
    ('Speech Pathologist', 5),
    ('Rehabilitation Counselor', 5),
    ('Licensed Clinical Social Worker', 5),
    ('Child Welfare Social Worker', 5),
    ('Palliative and Hospice Care Worker', 5),
    ('Special Education Teacher', 6),
    ('School Principal', 6),
    ('Superintendent', 6),
    ('College Professor', 6),
    ('School Librarian', 6),
    ('Substitute Teacher', 6),
    ('Archaeologist', 7),
    ('Software Engineer', 7),
    ('Laboratory Technician', 7),
    ('Microbiologist', 7),
    ('Physicist', 7),
    ('Auto Mechanic', 8),
    ('Landscaper and Groundskeeper', 8),
    ('Bicycle Repairer', 8),
    ('Wind Turbine Technician', 8),
    ('Plumber', 8),
    ('Agricultural Worker', 9),
    ('Animal Breeder', 9),
    ('Nursery Worker', 9),
    ('Forest and Conservation Worker', 9),
    ('Fisher', 9),
    ('Cafeteria Worker', 10),
    ('Congressional Staff', 10),
    ('National Park Ranger', 10),
    ('Mail Carrier', 10),
    ('Firefighter', 10),
    ('Anesthesiologist', 11),
    ('Dental Assistant', 11),
    ('Nurse', 11),
    ('Veterinarian', 11),
    ('Physical Therapist', 11),
    ('Lobbyist', 12),
    ('Public Administrator', 12),
    ('Paralegal', 12),
    ('Lawyer', 12),
    ('Labor Relations Specialist', 12),
    ('Sales Associate', 13),
    ('Sales Development Rep', 13),
    ('Account Executive', 13),
    ('Regional Sales Manager', 13),
    ('VP of Sales', 13);
